# Generated by Django 3.2.7 on 2021-09-24 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_landing_page', '0002_auto_20210924_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_landing_page.dadossite'),
        ),
    ]
